# Generated by Django 4.1.7 on 2023-03-09 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ShowplaceType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Enter showplace type",
                        max_length=20,
                        verbose_name="Showplace type",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Museum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Enter museum's name",
                        max_length=30,
                        verbose_name="Museum's name",
                    ),
                ),
                (
                    "summary",
                    models.TextField(
                        help_text="Enter summary",
                        max_length=1000,
                        verbose_name="Summary",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        help_text="Enter address", max_length=30, verbose_name="Address"
                    ),
                ),
                (
                    "telephone",
                    models.CharField(
                        help_text="Enter phone number",
                        max_length=13,
                        verbose_name="Phone number",
                    ),
                ),
                (
                    "price",
                    models.CharField(
                        help_text="Enter ticket's price",
                        max_length=10,
                        verbose_name="Ticket's price",
                    ),
                ),
                (
                    "schedule",
                    models.CharField(
                        help_text="Enter working hours in format 09:00-17:30",
                        max_length=11,
                        verbose_name="Working hours",
                    ),
                ),
                (
                    "dayoff",
                    models.CharField(
                        help_text="Enter dayoff", max_length=15, verbose_name="Dayoff"
                    ),
                ),
                (
                    "website",
                    models.CharField(
                        help_text="Enter web site address",
                        max_length=30,
                        verbose_name="Web site address",
                    ),
                ),
                (
                    "map_2gis",
                    models.CharField(
                        help_text="Enter 2gis map link",
                        max_length=50,
                        verbose_name="2gis",
                    ),
                ),
                (
                    "map_google",
                    models.CharField(
                        help_text="Enter Google map link",
                        max_length=50,
                        verbose_name="Google",
                    ),
                ),
                (
                    "latitude",
                    models.CharField(
                        help_text="Enter latitude",
                        max_length=20,
                        verbose_name="Latitude",
                    ),
                ),
                (
                    "longitude",
                    models.CharField(
                        help_text="Enter longitude",
                        max_length=20,
                        verbose_name="Longitude",
                    ),
                ),
                (
                    "showplace_type",
                    models.ForeignKey(
                        help_text="Choose showplace type",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.showplacetype",
                        verbose_name="Showplace type",
                    ),
                ),
            ],
        ),
    ]
